export const BRAND_COPY = Object.freeze({
  kr: Object.freeze({
    brandTag: '귀에 남은 소리를 적어두는 작은 음악 노트',
    navHome: '첫 장',
    navProfile: '내 기록',
    navNow: '오늘 들을 곡',
    navMatch: '둘이 듣기',
    homeEyebrow: '헤드폰을 쓰고 · 열 번의 짧은 선택',
    homeTitle: '말로는 늦게 알게 되는 마음을,\n귀는 먼저 알아챕니다.',
    homeDescription: '두 소리 가운데 조금 더 오래 남는 쪽을 고르세요. 열 번이면 충분합니다. 그날의 귀가 붙잡은 온도와 리듬을 적어두고, 지금 곁에 둘 다섯 곡으로 이어갑니다.',
    homeProfileTitle: '내가 자꾸 돌아가는 소리',
    homeProfileDesc: '열 번의 선택을 지나고 나면, 빠르기와 온도와 여백 사이에서 내가 오래 머무는 자리가 보입니다.',
    homeNowTitle: '오늘의 방에는 어떤 소리가 어울릴까요?',
    homeNowDesc: '일에 잠기고 싶은 오후, 말이 적어지는 밤, 조금은 가벼워지고 싶은 귀갓길. 지금의 장면을 고르면 다섯 곡을 차례로 건넵니다.',
    homeMatchTitle: '서로 다른 두 사람도 같은 후렴에서 멈출 때가 있습니다.',
    homeMatchDesc: '친구의 선택과 내 기록을 나란히 놓고, 어느 한쪽을 지우지 않은 채 함께 들을 다섯 곡을 고릅니다.',
    beginProfile: '첫 소리를 들어볼게요',
    continueProfile: '내가 남긴 기록 펼치기',
    openNow: '오늘 곁에 둘 다섯 곡',
    openMatch: '친구와 같이 들을 곡',
    existingProfile: '이 브라우저에 남아 있는 최근 기록',
    invitedTitle: '친구가 같은 노래 앞에 멈출 사람을 기다리고 있어요.',
    invitedDesc: '열 번의 선택을 마치면 두 사람 사이에 오래 남을 다섯 곡을 볼 수 있습니다.',
    legacyInvite: '예전 방식으로 만든 링크입니다. 지금의 여섯 방향으로 옮겨 읽습니다.',
    quizEyebrow: '열 번 듣고 고르기',
    quizAudio: '두 소리를 나란히',
    quizChoice: '한 장면을 고르기',
    preview: '잠깐 듣기',
    stop: '여기서 멈추기',
    choose: '이쪽이 더 남아요',
    questionOf: '번째 선택',
    quitQuiz: '첫 장으로 돌아가기',
    profileEyebrow: '내가 남긴 듣기 기록',
    profileMeaning: '사람을 한 문장으로 못 박는 검사가 아닙니다. 오늘의 귀가 어느 소리 곁에 오래 있었는지 적어둔 기록입니다.',
    profileShare: '친구에게 건네기',
    profileDownload: '한 장으로 저장하기',
    profileRetake: '다시 들어보기',
    profileNow: '이 기록으로 오늘의 곡 고르기',
    profileMatch: '친구와 둘이 들을 곡 찾기',
    profileAxes: '내 귀가 기운 여섯 방향',
    profileWhy: '왜 이 장면이 남았을까요',
    profileSaved: '이 브라우저에 조용히 보관됨',
    nowEyebrow: '오늘의 다섯 곡',
    nowTitle: '지금 있는 곳과 마음의 속도를 골라주세요.',
    nowDescription: '익숙한 자리에서 세 곡을 고르고, 한 걸음 옆의 곡 하나와 조금 먼 곳의 곡 하나를 섞습니다. 무리해서 새로워지지 않아도 됩니다.',
    nowResultTitle: '지금부터 차례로 들을 다섯 곡',
    nowChange: '다른 장면으로 다시 고르기',
    nowNeedProfile: '먼저 열 번의 선택을 남겨주세요. 그래야 지금의 장면과 닿는 곡을 고를 수 있습니다.',
    listenSpotify: 'Spotify에서 열기',
    listenYoutube: 'YouTube에서 열기',
    listenApple: 'Apple Music에서 열기',
    matchEyebrow: '두 사람 사이의 음악',
    matchTitle: '닮지 않아도, 같은 곡을 오래 들을 수 있습니다.',
    matchInviteTitle: '이 링크를 친구에게 건네주세요.',
    matchInviteDesc: '친구도 열 번을 고르면 둘 사이에 놓을 다섯 곡을 찾습니다. 이름과 연락처는 묻지 않습니다.',
    matchShare: '친구에게 보내기',
    matchCopy: '링크 복사하기',
    matchPasteLabel: '친구가 보낸 링크',
    matchPastePlaceholder: '받은 링크를 여기에 붙여넣기',
    matchLoad: '둘 사이의 곡 보기',
    matchYou: '내가 머무는 소리',
    matchFriend: '친구가 머무는 소리',
    matchCommon: '둘이 함께 편안한 자리',
    matchDifference: '서로에게 건넬 수 있는 낯선 자리',
    matchPlaylist: '두 사람 사이에 놓을 다섯 곡',
    matchNoCommon: '같은 취향이 아니어도 괜찮습니다. 두 사람이 함께 앉을 수 있는 작은 중간을 찾았습니다.',
    matchNoDifference: '서로의 선택이 이미 무리 없이 이어집니다. 같은 곡을 두고 다른 이유로 좋아해도 좋습니다.',
    copySuccess: '링크를 복사했습니다.',
    shareCancelled: '보내지 않고 돌아왔습니다.',
    shareError: '링크를 준비하지 못했습니다. 잠시 뒤 다시 시도해주세요.',
    invalidInvite: '읽을 수 없는 링크입니다. 친구에게 새 링크를 부탁해주세요.',
    resetConfirm: '지금까지 남긴 기록을 지우고 처음부터 들을까요?',
    profileCleared: '브라우저에 남아 있던 취향 기록을 지웠습니다.',
    footerPrivacy: '기록이 남는 방식',
    footerNote: '취향과 주간 기록은 이 브라우저에 보관됩니다. 이 서비스는 음악을 고르고 기억하기 위한 노트이지, 사람을 진단하는 검사가 아닙니다.',
    close: '닫기',
    boothLabel: '첫 번째 선택 · 열 번 중 하나',
    boothTitle: '두 소리 가운데, 어느 쪽이 조금 더 오래 남나요?',
    boothHint: '이유를 찾지 않아도 됩니다. 끝난 뒤에도 귀 안에 남아 있는 쪽이면 충분합니다.',
    boothContinue: '이 소리에서 시작하기',
    boothHeard: '한 번 들어봄',
    sampleEyebrow: '다른 사람의 한 장',
    sampleTitle: '좋아하는 노래를 따라가면, 자주 돌아가는 장면이 보입니다.',
    sampleBody: '창문에 비가 붙던 밤, 혼자 오래 걸었던 길, 누군가와 같은 후렴을 부르던 순간. 음악 취향은 그런 장면들 곁에 남습니다.',
    sampleTracks: '이 장면의 불을 오래 켜두는 세 곡',
    todayEyebrow: '지금의 시간',
    todayTitle: '오늘의 마음에는 오늘의 순서가 있습니다.',
    todayBody: '익숙한 세 곡으로 문을 열고, 한 곡만 옆길로 샙니다. 마지막 한 곡은 내일의 귀에 남겨둡니다.',
    togetherEyebrow: '둘 사이에 놓인 음악',
    togetherTitle: '다른 길을 걸어온 두 사람도 같은 노래 앞에서는 걸음을 늦춥니다.',
    togetherBody: '얼마나 닮았는지 세기보다, 둘이 함께 있을 때 어색하지 않은 온도와 박자를 찾습니다.',
    togetherYouLabel: '내 쪽의 불빛',
    togetherFriendLabel: '친구 쪽의 불빛',
    togetherBridgeLabel: '두 불빛 사이에 남는 것',
    togetherBridgeNote: '한 사람은 잔향을 오래 듣고, 한 사람은 박자에 먼저 몸을 맡깁니다. 둘 사이에는 따뜻한 후렴이 천천히 자리를 잡습니다.',
    togetherEaseLabel: '함께 오래 들어도 편한 정도',
    togetherDiscoveryLabel: '서로에게 새 곡을 건넬 여지',
    privacyTitle: '이 기록은 멀리 가지 않습니다.',
    privacyBody: '이름과 계정은 묻지 않습니다. 취향과 주간 기록은 이 브라우저 안에 머물고, 친구에게는 여섯 개의 숫자와 익명 ID만 건너갑니다.',
    viewSample: '다른 사람의 기록 한 장 보기'
  }),
  en: Object.freeze({
    brandTag: 'A small notebook for the sounds that stayed',
    navHome: 'First page',
    navProfile: 'My notes',
    navNow: 'For today',
    navMatch: 'For two',
    homeEyebrow: 'Headphones on · ten brief choices',
    homeTitle: 'The heart is often late with words.\nThe ear notices first.',
    homeDescription: 'Between two sounds, choose the one that lingers. Ten choices are enough. We write down the temperature and pulse your ear held onto, then carry them into five songs for now.',
    homeProfileTitle: 'The sound I keep returning to',
    homeProfileDesc: 'After ten choices, a place begins to appear between speed, warmth, space, and company—the place where you tend to stay.',
    homeNowTitle: 'What belongs in the room today?',
    homeNowDesc: 'An afternoon that needs concentration, a quiet walk home, a night with fewer words. Choose the scene and we will set five songs beside it.',
    homeMatchTitle: 'Two different listeners can still slow down at the same chorus.',
    homeMatchDesc: 'We place your notes beside a friend’s and choose five songs without erasing either person.',
    beginProfile: 'Hear the first sound',
    continueProfile: 'Open my listening notes',
    openNow: 'Five songs to keep nearby',
    openMatch: 'Find music for two',
    existingProfile: 'The latest note kept in this browser',
    invitedTitle: 'A friend is waiting to see where your listening meets.',
    invitedDesc: 'Make ten choices and we will find five songs that can live between the two of you.',
    legacyInvite: 'This link came from an earlier version. We will read it through the current six directions.',
    quizEyebrow: 'Ten small acts of listening',
    quizAudio: 'Two sounds, side by side',
    quizChoice: 'Choose one scene',
    preview: 'Listen for a moment',
    stop: 'Stop here',
    choose: 'This one stays longer',
    questionOf: 'choice',
    quitQuiz: 'Return to the first page',
    profileEyebrow: 'The listening note I left',
    profileMeaning: 'This is not a sentence handed down about who you are. It is a note about where your ear rested today.',
    profileShare: 'Pass it to a friend',
    profileDownload: 'Save this page',
    profileRetake: 'Listen again',
    profileNow: 'Choose today’s songs from this note',
    profileMatch: 'Find five songs for two',
    profileAxes: 'Six directions my ear leaned',
    profileWhy: 'Why did this scene remain?',
    profileSaved: 'Kept quietly in this browser',
    nowEyebrow: 'Five songs for now',
    nowTitle: 'Choose the room you are in and the speed of your thoughts.',
    nowDescription: 'Three songs stay close to what you know. One steps sideways. One comes from a little farther off. Nothing has to be new for the sake of being new.',
    nowResultTitle: 'Five songs, in the order to hear them',
    nowChange: 'Choose another scene',
    nowNeedProfile: 'Leave ten choices first. Then we can find songs that belong beside this moment.',
    listenSpotify: 'Open in Spotify',
    listenYoutube: 'Open in YouTube',
    listenApple: 'Open in Apple Music',
    matchEyebrow: 'Music between two people',
    matchTitle: 'You do not have to be alike to stay with the same song.',
    matchInviteTitle: 'Pass this link to a friend.',
    matchInviteDesc: 'When your friend has made ten choices, we will find five songs to place between you. No name or contact information is asked for.',
    matchShare: 'Send to a friend',
    matchCopy: 'Copy the link',
    matchPasteLabel: 'The link your friend sent',
    matchPastePlaceholder: 'Paste the link here',
    matchLoad: 'See the songs between you',
    matchYou: 'Where my ear stays',
    matchFriend: 'Where my friend’s ear stays',
    matchCommon: 'A place that feels easy for both',
    matchDifference: 'A place where one person can offer something new',
    matchPlaylist: 'Five songs to set between you',
    matchNoCommon: 'You do not need the same taste. We found a small middle where both of you can sit.',
    matchNoDifference: 'Your choices already follow one another without strain. The same song may still matter for different reasons.',
    copySuccess: 'The link is copied.',
    shareCancelled: 'You came back without sending it.',
    shareError: 'The link could not be prepared. Please try again in a moment.',
    invalidInvite: 'This link cannot be read. Ask your friend for a new one.',
    resetConfirm: 'Clear the notes kept so far and listen from the beginning?',
    profileCleared: 'The saved listening notes have been cleared.',
    footerPrivacy: 'How these notes are kept',
    footerNote: 'Taste and weekly notes stay in this browser. This is a notebook for choosing and remembering music, not a test that diagnoses a person.',
    close: 'Close',
    boothLabel: 'First choice · one of ten',
    boothTitle: 'Which of these two sounds remains a little longer?',
    boothHint: 'You do not need a reason. The one still present after it ends is enough.',
    boothContinue: 'Begin with this sound',
    boothHeard: 'Heard once',
    sampleEyebrow: 'A page from another listener',
    sampleTitle: 'Follow the songs you love and the scenes you return to begin to show.',
    sampleBody: 'Rain holding to a window, a long walk alone, a chorus sung beside someone else. Taste often remains close to such scenes.',
    sampleTracks: 'Three songs that keep the light on in this scene',
    todayEyebrow: 'The hour at hand',
    todayTitle: 'Today’s feeling has its own order of songs.',
    todayBody: 'Open the door with three familiar songs. Let one take a side road. Leave the last one for tomorrow’s ear.',
    togetherEyebrow: 'Music laid between two people',
    togetherTitle: 'People who came by different roads can still slow down at the same song.',
    togetherBody: 'Rather than count how alike you are, we look for a temperature and pulse that do not feel awkward when shared.',
    togetherYouLabel: 'The light on my side',
    togetherFriendLabel: 'The light on my friend’s side',
    togetherBridgeLabel: 'What remains between the two lights',
    togetherBridgeNote: 'One person stays with the afterglow; the other gives the body to the beat first. Between them, a warm chorus slowly finds a place.',
    togetherEaseLabel: 'How easy it is to keep listening together',
    togetherDiscoveryLabel: 'Room to hand each other a new song',
    privacyTitle: 'These notes do not travel far.',
    privacyBody: 'We ask for no name or account. Taste and weekly notes stay in this browser; only six values and an anonymous ID pass to a friend.',
    viewSample: 'Open a page from another listener'
  })
});
