export const BRAND_COPY = Object.freeze({
  kr: Object.freeze({
    brandTag: '듣고, 고르고, 같이 발견하는 음악 취향',
    navHome: '처음',
    navProfile: '내 취향',
    navNow: '오늘의 선곡',
    navMatch: '같이 듣기',
    homeEyebrow: '10번의 음악 선택 · 약 90초',
    homeTitle: '내가 좋아하는 소리엔\n이유가 있어요.',
    homeDescription: '짧은 음악을 듣고 더 끌리는 쪽을 골라보세요. 내 취향을 여섯 가지 방향으로 보여드리고, 오늘 들을 곡까지 함께 찾습니다.',
    homeProfileTitle: '내 취향의 모양',
    homeProfileDesc: '열 번의 선택이 내가 오래 머무는 소리의 방향을 보여줍니다.',
    homeNowTitle: '오늘은 어떤 음악이 필요하나요?',
    homeNowDesc: '집중, 회복, 밤 산책처럼 지금의 장면을 고르면 내 취향에 맞는 다섯 곡을 찾습니다.',
    homeMatchTitle: '서로 다른 취향 사이에도 같이 들을 곡은 있어요.',
    homeMatchDesc: '친구가 같은 선택을 마치면 두 사람에게 모두 잘 맞는 다섯 곡을 고릅니다.',
    beginProfile: '첫 번째 소리 듣기',
    continueProfile: '내 취향 다시 보기',
    openNow: '오늘 들을 곡 찾기',
    openMatch: '친구와 같이 듣기',
    existingProfile: '이 브라우저에 저장된 취향',
    invitedTitle: '친구가 같이 들을 곡을 찾고 있어요.',
    invitedDesc: '내 선택을 마치면 두 사람의 공명도와 같이 들을 다섯 곡을 바로 볼 수 있어요.',
    legacyInvite: '예전 결과 링크예요. 지금의 취향 방식으로 바꿔서 비교합니다.',
    quizEyebrow: '10번 듣고 고르기',
    quizAudio: '두 소리 비교',
    quizChoice: '한 장면 고르기',
    preview: '들어보기',
    stop: '멈추기',
    choose: '이 소리가 더 좋아요',
    questionOf: '번째 선택',
    quitQuiz: '처음으로',
    profileEyebrow: 'MY LISTENING NOTES',
    profileMeaning: '한 번의 진단이 아니라, 지금 내가 오래 머무는 소리를 기록한 결과예요.',
    profileShare: '친구에게 보내기',
    profileDownload: '이미지로 저장',
    profileRetake: '다시 들어보기',
    profileNow: '이 취향으로 오늘의 5곡 고르기',
    profileMatch: '친구와 같이 들을 곡 찾기',
    profileAxes: '내 취향이 머무는 여섯 방향',
    profileWhy: '왜 이런 취향이 나왔나요?',
    profileSaved: '이 브라우저에 저장됨',
    nowEyebrow: 'TODAY’S LISTEN',
    nowTitle: '지금 필요한 분위기를 골라보세요.',
    nowDescription: '내 취향을 크게 벗어나지 않으면서 지금에 맞는 다섯 곡을 고릅니다. 한 곡은 조금 낯선 방향으로 섞어요.',
    nowResultTitle: '지금 들을 5곡',
    nowChange: '다른 분위기 고르기',
    nowNeedProfile: '먼저 짧은 음악을 듣고 내 취향을 만들어주세요. 그다음 지금에 맞는 곡을 고를 수 있어요.',
    listenSpotify: 'Spotify',
    listenYoutube: 'YouTube',
    listenApple: 'Apple Music',
    matchEyebrow: 'LISTEN TOGETHER',
    matchTitle: '서로 다른 취향 사이에도 같이 들을 곡은 있어요.',
    matchInviteTitle: '친구에게 이 링크를 보내세요.',
    matchInviteDesc: '친구가 열 번의 선택을 마치면 둘에게 잘 맞는 다섯 곡을 찾아드려요. 이름이나 연락처는 담지 않아요.',
    matchShare: '친구에게 보내기',
    matchCopy: '링크만 복사',
    matchPasteLabel: '친구에게 받은 링크',
    matchPastePlaceholder: '링크를 붙여넣으세요',
    matchLoad: '같이 듣기',
    matchYou: '내 취향',
    matchFriend: '친구 취향',
    matchCommon: '함께 오래 들을 지점',
    matchDifference: '서로에게 새로울 지점',
    matchPlaylist: '둘이 들을 5곡',
    matchNoCommon: '완전히 닮지 않아도 함께 들을 수 있는 중간 지점을 찾았어요.',
    matchNoDifference: '서로의 선택이 자연스럽게 이어지는 취향이에요.',
    copySuccess: '링크를 복사했어요.',
    shareCancelled: '공유를 취소했어요.',
    shareError: '링크를 준비하지 못했어요.',
    invalidInvite: '읽을 수 있는 취향 링크가 아니에요.',
    resetConfirm: '저장된 취향을 지우고 다시 시작할까요?',
    profileCleared: '저장된 취향을 지웠어요.',
    footerPrivacy: '데이터 안내',
    footerNote: '내 취향은 이 브라우저에 저장됩니다. 결과와 추천은 음악을 발견하고 기록하기 위한 참고이며 전문적인 심리 진단이 아닙니다.',
    close: '닫기',
    boothLabel: '01 / 10 · 듣고 고르기',
    boothTitle: '어느 쪽에 더 오래 머물고 싶나요?',
    boothHint: '정답은 없어요. 설명보다 소리를 먼저 들어보세요.',
    boothContinue: '이 선택으로 계속하기',
    boothHeard: '들어봄',
    sampleEyebrow: 'A LISTENING NOTE',
    sampleTitle: '취향은 한 단어보다 모양에 가까워요.',
    sampleBody: '잔잔함과 강렬함, 익숙함과 새로움, 혼자 듣기와 함께 듣기 사이에서 내가 오래 머무는 지점을 기록합니다.',
    sampleTracks: '이 취향을 설명하는 세 곡',
    todayEyebrow: 'A MOMENT, FIVE TRACKS',
    todayTitle: '지금의 장면을 고르면 선곡이 달라집니다.',
    todayBody: '내 취향과 가까운 세 곡, 한 걸음 옆의 한 곡, 조금 낯선 한 곡을 섞습니다.',
    togetherEyebrow: 'TWO TASTES, ONE LIST',
    togetherTitle: '같다는 것보다, 같이 들을 수 있다는 것.',
    togetherBody: '공명도는 닮은 정도를, 발견 가능성은 서로의 선곡을 넓힐 여지를 보여줍니다.',
    privacyTitle: '회원가입 없이 시작해요.',
    privacyBody: '선택 결과는 이 브라우저에 저장됩니다. 친구 링크에는 이름이나 연락처 대신 여섯 개의 취향 값만 담깁니다.',
    viewSample: '결과 예시 보기'
  }),
  en: Object.freeze({
    brandTag: 'Listen, choose, and discover music together',
    navHome: 'Start',
    navProfile: 'My taste',
    navNow: 'For today',
    navMatch: 'Listen together',
    homeEyebrow: '10 music choices · about 90 seconds',
    homeTitle: 'There is a reason\nsome sounds stay with you.',
    homeDescription: 'Listen to short clips and choose the ones that pull you in. We will map the shape of your taste, then help you find music for today.',
    homeProfileTitle: 'The shape of my taste',
    homeProfileDesc: 'Ten choices reveal the directions your listening returns to most often.',
    homeNowTitle: 'What do you need to hear today?',
    homeNowDesc: 'Choose a moment—focus, reset, a night walk—and get five tracks that still feel like you.',
    homeMatchTitle: 'Different tastes can still share a good track.',
    homeMatchDesc: 'When a friend makes their choices, we find five tracks with room for both of you.',
    beginProfile: 'Hear the first pair',
    continueProfile: 'Open my taste notes',
    openNow: 'Find music for today',
    openMatch: 'Listen with a friend',
    existingProfile: 'Taste notes saved in this browser',
    invitedTitle: 'A friend is looking for music you can share.',
    invitedDesc: 'Finish your choices to see where you resonate and hear five tracks for both of you.',
    legacyInvite: 'This came from an earlier result. We will translate it into the current taste model.',
    quizEyebrow: 'Listen and choose · 10 times',
    quizAudio: 'Compare two sounds',
    quizChoice: 'Choose a scene',
    preview: 'Listen',
    stop: 'Stop',
    choose: 'I would stay with this one',
    questionOf: 'choice',
    quitQuiz: 'Back to start',
    profileEyebrow: 'MY LISTENING NOTES',
    profileMeaning: 'This is not a fixed diagnosis. It is a note about the sounds you are drawn to right now.',
    profileShare: 'Send to a friend',
    profileDownload: 'Save as an image',
    profileRetake: 'Listen again',
    profileNow: 'Choose five tracks for today',
    profileMatch: 'Find music for two',
    profileAxes: 'Six directions in my taste',
    profileWhy: 'Why did this taste appear?',
    profileSaved: 'Saved in this browser',
    nowEyebrow: 'TODAY’S LISTEN',
    nowTitle: 'Choose the atmosphere you need right now.',
    nowDescription: 'We stay near your taste, choose five tracks for the moment, and leave one space for something less familiar.',
    nowResultTitle: 'Five tracks for now',
    nowChange: 'Choose another atmosphere',
    nowNeedProfile: 'First, listen to a few short clips and make your taste notes. Then we can choose music for the moment.',
    listenSpotify: 'Spotify',
    listenYoutube: 'YouTube',
    listenApple: 'Apple Music',
    matchEyebrow: 'LISTEN TOGETHER',
    matchTitle: 'Different tastes can still share a good track.',
    matchInviteTitle: 'Send this link to a friend.',
    matchInviteDesc: 'After ten choices, we will find five tracks that leave room for both of you. The link contains no name or contact information.',
    matchShare: 'Send to a friend',
    matchCopy: 'Copy the link',
    matchPasteLabel: 'Link from a friend',
    matchPastePlaceholder: 'Paste the link here',
    matchLoad: 'Listen together',
    matchYou: 'My taste',
    matchFriend: 'Friend’s taste',
    matchCommon: 'Where you can stay together',
    matchDifference: 'Where each person adds something new',
    matchPlaylist: 'Five tracks for two',
    matchNoCommon: 'You do not need identical scores to find a useful middle ground.',
    matchNoDifference: 'Your choices already flow into each other naturally.',
    copySuccess: 'Link copied.',
    shareCancelled: 'Share cancelled.',
    shareError: 'Could not prepare the link.',
    invalidInvite: 'This taste link could not be read.',
    resetConfirm: 'Clear the saved taste notes and start again?',
    profileCleared: 'Saved taste notes cleared.',
    footerPrivacy: 'Data notes',
    footerNote: 'Your taste notes stay in this browser. Results and recommendations are for music discovery and reflection, not professional psychological diagnosis.',
    close: 'Close',
    boothLabel: '01 / 10 · LISTEN & CHOOSE',
    boothTitle: 'Which one would you stay with a little longer?',
    boothHint: 'There is no right answer. Listen before reading too much into it.',
    boothContinue: 'Continue with this choice',
    boothHeard: 'Heard',
    sampleEyebrow: 'A LISTENING NOTE',
    sampleTitle: 'Taste is closer to a shape than a single word.',
    sampleBody: 'We note where you stay between calm and charged, familiar and exploratory, private and shared listening.',
    sampleTracks: 'Three tracks that explain this taste',
    todayEyebrow: 'A MOMENT, FIVE TRACKS',
    todayTitle: 'The list changes with the moment.',
    todayBody: 'Three close fits, one step to the side, and one track that is intentionally less familiar.',
    togetherEyebrow: 'TWO TASTES, ONE LIST',
    togetherTitle: 'Not the same—just good to listen to together.',
    togetherBody: 'Resonance shows where you already meet. Discovery shows where one person can widen the other’s listening.',
    privacyTitle: 'Start without an account.',
    privacyBody: 'Your choices stay in this browser. Friend links carry six taste values, not a name or contact details.',
    viewSample: 'See a sample result'
  })
});
