export const BRAND_COPY = Object.freeze({
  kr: Object.freeze({
    brandTag: '듣고, 고르고, 같이 발견하는 음악 취향',
    navHome: '처음',
    navProfile: '내 취향',
    navNow: '오늘의 선곡',
    navMatch: '같이 듣기',
    homeEyebrow: '헤드폰을 쓰고 · 열 번만 들어보세요',
    homeTitle: '설명하기 어려운 노래도,\n마음은 먼저 알아봐요.',
    homeDescription: '자꾸 귀가 머무는 쪽을 열 번 골라보세요. 당신이 좋아하는 소리의 결을 찾아, 오늘의 시간과 함께 들을 곡으로 이어드릴게요.',
    homeProfileTitle: '내 취향의 모양',
    homeProfileDesc: '열 번의 선택이 내가 오래 머무는 소리의 방향을 보여줍니다.',
    homeNowTitle: '오늘은 어떤 음악이 필요하나요?',
    homeNowDesc: '집중, 회복, 밤 산책처럼 지금의 장면을 고르면 내 취향에 맞는 다섯 곡을 찾습니다.',
    homeMatchTitle: '서로 다른 취향 사이에도 같이 들을 곡은 있어요.',
    homeMatchDesc: '친구가 같은 선택을 마치면 두 사람에게 모두 잘 맞는 다섯 곡을 고릅니다.',
    beginProfile: '첫 소리부터 들어보기',
    continueProfile: '내가 남긴 소리 다시 보기',
    openNow: '오늘의 마음에 맞는 5곡',
    openMatch: '친구와 한 곡부터 이어보기',
    existingProfile: '이 브라우저에 남아 있는 듣기 기록',
    invitedTitle: '친구가 같이 들을 곡을 찾고 있어요.',
    invitedDesc: '내 선택을 마치면 두 사람의 공명도와 같이 들을 다섯 곡을 바로 볼 수 있어요.',
    legacyInvite: '예전 결과 링크예요. 지금의 취향 방식으로 바꿔서 비교합니다.',
    quizEyebrow: '10번 듣고 고르기',
    quizAudio: '두 소리 비교',
    quizChoice: '한 장면 고르기',
    preview: '들어보기',
    stop: '멈추기',
    choose: '이 소리가 더 좋아요',
    questionOf: '번째 선택',
    quitQuiz: '처음으로',
    profileEyebrow: '나의 듣기 기록',
    profileMeaning: '한 번의 진단이 아니라, 지금 내가 오래 머무는 소리를 기록한 결과예요.',
    profileShare: '친구에게 보내기',
    profileDownload: '이미지로 저장',
    profileRetake: '다시 들어보기',
    profileNow: '이 취향으로 오늘의 5곡 고르기',
    profileMatch: '친구와 같이 들을 곡 찾기',
    profileAxes: '내 취향이 머무는 여섯 방향',
    profileWhy: '왜 이런 취향이 나왔나요?',
    profileSaved: '이 브라우저에 저장됨',
    nowEyebrow: '오늘의 듣기',
    nowTitle: '지금 필요한 분위기를 골라보세요.',
    nowDescription: '내 취향을 크게 벗어나지 않으면서 지금에 맞는 다섯 곡을 고릅니다. 한 곡은 조금 낯선 방향으로 섞어요.',
    nowResultTitle: '지금 들을 5곡',
    nowChange: '다른 분위기 고르기',
    nowNeedProfile: '먼저 짧은 음악을 듣고 내 취향을 만들어주세요. 그다음 지금에 맞는 곡을 고를 수 있어요.',
    listenSpotify: 'Spotify',
    listenYoutube: 'YouTube',
    listenApple: 'Apple Music',
    matchEyebrow: '같이 듣기',
    matchTitle: '서로 다른 취향 사이에도 같이 들을 곡은 있어요.',
    matchInviteTitle: '친구에게 이 링크를 보내세요.',
    matchInviteDesc: '친구가 열 번의 선택을 마치면 둘에게 잘 맞는 다섯 곡을 찾아드려요. 이름이나 연락처는 담지 않아요.',
    matchShare: '친구에게 보내기',
    matchCopy: '링크만 복사',
    matchPasteLabel: '친구에게 받은 링크',
    matchPastePlaceholder: '링크를 붙여넣으세요',
    matchLoad: '같이 듣기',
    matchYou: '내 취향',
    matchFriend: '친구 취향',
    matchCommon: '함께 오래 들을 지점',
    matchDifference: '서로에게 새로울 지점',
    matchPlaylist: '둘이 들을 5곡',
    matchNoCommon: '완전히 닮지 않아도 함께 들을 수 있는 중간 지점을 찾았어요.',
    matchNoDifference: '서로의 선택이 자연스럽게 이어지는 취향이에요.',
    copySuccess: '링크를 복사했어요.',
    shareCancelled: '공유를 취소했어요.',
    shareError: '링크를 준비하지 못했어요.',
    invalidInvite: '읽을 수 있는 취향 링크가 아니에요.',
    resetConfirm: '저장된 취향을 지우고 다시 시작할까요?',
    profileCleared: '저장된 취향을 지웠어요.',
    footerPrivacy: '데이터 안내',
    footerNote: '내 취향은 이 브라우저에 저장됩니다. 결과와 추천은 음악을 발견하고 기록하기 위한 참고이며 전문적인 심리 진단이 아닙니다.',
    close: '닫기',
    boothLabel: '첫 번째 선택 · 10번 중 1번',
    boothTitle: '지금, 어느 쪽에 마음이 조금 더 가나요?',
    boothHint: '잘 고르려 하지 않아도 돼요. 먼저 귀에 남는 쪽이면 충분해요.',
    boothContinue: '이 소리를 따라가볼게요',
    boothHeard: '들어봄',
    sampleEyebrow: '취향을 한 장에 담으면',
    sampleTitle: '좋아하는 음악은, 자꾸 돌아가는 장면을 닮아요.',
    sampleBody: '비 오는 밤, 혼자 걷는 길, 누군가와 나누고 싶은 후렴. 열 번의 선택으로 당신이 다시 찾는 소리의 결을 남깁니다.',
    sampleTracks: '이 장면을 오래 남기는 세 곡',
    todayEyebrow: '오늘의 장면',
    todayTitle: '오늘의 마음에는, 오늘의 순서가 있어요.',
    todayBody: '익숙한 세 곡으로 시작해 한 걸음 옆으로 가고, 마지막에는 작은 낯섦 하나를 남깁니다.',
    togetherEyebrow: '둘 사이의 선곡',
    togetherTitle: '취향이 달라도, 같은 순간에 멈추는 곡이 있어요.',
    togetherBody: '닮은 정도를 재기보다, 두 사람 사이에서 자연스럽게 이어지는 온도와 리듬을 찾습니다.',
    togetherYouLabel: '내가 머무는 쪽',
    togetherFriendLabel: '친구가 머무는 쪽',
    togetherBridgeLabel: '둘 사이에 남는 소리',
    togetherBridgeNote: '한 사람은 잔향에, 한 사람은 리듬에 머물러요. 둘 사이에서는 따뜻한 후렴이 오래 남습니다.',
    togetherEaseLabel: '함께 편안한 정도',
    togetherDiscoveryLabel: '새 곡을 건넬 여지',
    privacyTitle: '이 기록은 당신의 브라우저 안에 머물러요.',
    privacyBody: '이름도 계정도 묻지 않습니다. 친구에게는 취향의 모양만 건네고, 개인 정보는 남기지 않아요.',
    viewSample: '다른 사람의 듣기 기록 보기'
  }),
  en: Object.freeze({
    brandTag: 'Listen, choose, and discover music together',
    navHome: 'Start',
    navProfile: 'My taste',
    navNow: 'For today',
    navMatch: 'Listen together',
    homeEyebrow: 'Put on headphones · listen ten times',
    homeTitle: 'Some songs are hard to explain.\nYour ears know before words do.',
    homeDescription: 'Choose the sound you keep leaning toward, ten times. We will trace the texture you return to and carry it into five songs for today.',
    homeProfileTitle: 'The shape of my taste',
    homeProfileDesc: 'Ten choices reveal the directions your listening returns to most often.',
    homeNowTitle: 'What do you need to hear today?',
    homeNowDesc: 'Choose a moment—focus, reset, a night walk—and get five tracks that still feel like you.',
    homeMatchTitle: 'Different tastes can still share a good track.',
    homeMatchDesc: 'When a friend makes their choices, we find five tracks with room for both of you.',
    beginProfile: 'Hear the first pair',
    continueProfile: 'Reopen what I heard',
    openNow: 'Find five songs for today',
    openMatch: 'Start one song with a friend',
    existingProfile: 'A listening note saved in this browser',
    invitedTitle: 'A friend is looking for music you can share.',
    invitedDesc: 'Finish your choices to see where you resonate and hear five tracks for both of you.',
    legacyInvite: 'This came from an earlier result. We will translate it into the current taste model.',
    quizEyebrow: 'Listen and choose · 10 times',
    quizAudio: 'Compare two sounds',
    quizChoice: 'Choose a scene',
    preview: 'Listen',
    stop: 'Stop',
    choose: 'I would stay with this one',
    questionOf: 'choice',
    quitQuiz: 'Back to start',
    profileEyebrow: 'MY LISTENING NOTES',
    profileMeaning: 'This is not a fixed diagnosis. It is a note about the sounds you are drawn to right now.',
    profileShare: 'Send to a friend',
    profileDownload: 'Save as an image',
    profileRetake: 'Listen again',
    profileNow: 'Choose five tracks for today',
    profileMatch: 'Find music for two',
    profileAxes: 'Six directions in my taste',
    profileWhy: 'Why did this taste appear?',
    profileSaved: 'Saved in this browser',
    nowEyebrow: 'TODAY’S LISTEN',
    nowTitle: 'Choose the atmosphere you need right now.',
    nowDescription: 'We stay near your taste, choose five tracks for the moment, and leave one space for something less familiar.',
    nowResultTitle: 'Five tracks for now',
    nowChange: 'Choose another atmosphere',
    nowNeedProfile: 'First, listen to a few short clips and make your taste notes. Then we can choose music for the moment.',
    listenSpotify: 'Spotify',
    listenYoutube: 'YouTube',
    listenApple: 'Apple Music',
    matchEyebrow: 'LISTEN TOGETHER',
    matchTitle: 'Different tastes can still share a good track.',
    matchInviteTitle: 'Send this link to a friend.',
    matchInviteDesc: 'After ten choices, we will find five tracks that leave room for both of you. The link contains no name or contact information.',
    matchShare: 'Send to a friend',
    matchCopy: 'Copy the link',
    matchPasteLabel: 'Link from a friend',
    matchPastePlaceholder: 'Paste the link here',
    matchLoad: 'Listen together',
    matchYou: 'My taste',
    matchFriend: 'Friend’s taste',
    matchCommon: 'Where you can stay together',
    matchDifference: 'Where each person adds something new',
    matchPlaylist: 'Five tracks for two',
    matchNoCommon: 'You do not need identical scores to find a useful middle ground.',
    matchNoDifference: 'Your choices already flow into each other naturally.',
    copySuccess: 'Link copied.',
    shareCancelled: 'Share cancelled.',
    shareError: 'Could not prepare the link.',
    invalidInvite: 'This taste link could not be read.',
    resetConfirm: 'Clear the saved taste notes and start again?',
    profileCleared: 'Saved taste notes cleared.',
    footerPrivacy: 'Data notes',
    footerNote: 'Your taste notes stay in this browser. Results and recommendations are for music discovery and reflection, not professional psychological diagnosis.',
    close: 'Close',
    boothLabel: 'FIRST CHOICE · 1 OF 10',
    boothTitle: 'Which one is your ear leaning toward right now?',
    boothHint: 'You do not need to choose well. The one that stays a little longer is enough.',
    boothContinue: 'Follow this sound',
    boothHeard: 'Heard',
    sampleEyebrow: 'A TASTE, HELD ON ONE PAGE',
    sampleTitle: 'The music you love often resembles the scenes you return to.',
    sampleBody: 'A rainy night, a walk alone, a chorus you want to share. Ten choices leave a note about the texture you keep coming back to.',
    sampleTracks: 'Three songs that keep this scene alive',
    todayEyebrow: 'A MOMENT FOR TODAY',
    todayTitle: 'Today’s feeling has its own listening order.',
    todayBody: 'Start with three familiar songs, take one step to the side, and leave a small unfamiliar sound at the end.',
    togetherEyebrow: 'THE SPACE BETWEEN TWO TASTES',
    togetherTitle: 'Different tastes can still stop at the same song.',
    togetherBody: 'Instead of measuring how alike you are, we look for the warmth and rhythm that move naturally between two people.',
    togetherYouLabel: 'Where I tend to stay',
    togetherFriendLabel: 'Where my friend tends to stay',
    togetherBridgeLabel: 'What remains between you',
    togetherBridgeNote: 'One person stays with the afterglow, the other with the rhythm. Between them, a warm chorus lasts.',
    togetherEaseLabel: 'Ease together',
    togetherDiscoveryLabel: 'Room to share something new',
    privacyTitle: 'This note stays inside your browser.',
    privacyBody: 'We do not ask for a name or account. A friend receives only the shape of your taste, not personal information.',
    viewSample: 'See another listening note'
  })
});
