export const M4_COPY = Object.freeze({
  kr: Object.freeze({
    navWeekly: 'Weekly',
    openWeekly: '이번 주 Vibe 보기',
    weeklyReady: '이번 주 리캡이 준비됐어요',
    weeklyCollecting: 'Weekly Vibe를 모으는 중',
    weeklyReturn: '7일 동안 쌓인 취향을 확인해보세요',
    weeklyEyebrow: 'WEEKLY VIBE',
    weeklyTitle: '이번 주, 당신의 취향은 어디로 움직였을까요?',
    weeklyDescription: '최근 7일의 상황 선택, 곡 클릭, 선호 피드백으로 만든 로컬 리캡이에요.',
    weeklyNeedMore: 'Weekly Vibe를 만들려면 상호작용이 조금 더 필요해요.',
    weeklyRemaining: '번 더 곡을 고르거나 피드백을 남겨보세요.',
    weeklyContext: '가장 자주 찾은 순간',
    weeklyTags: '이번 주의 사운드',
    weeklyTracks: '다시 듣고 싶은 곡',
    weeklyChanges: '평소 프로필에서 달라진 지점',
    weeklyShare: '주간 카드 공유',
    weeklyDownload: '주간 카드 저장',
    feedbackMore: '더 듣고 싶어요',
    feedbackLess: '덜 듣고 싶어요',
    feedbackSaved: '다음 추천에 반영했어요.',
    timeline: '프로필 타임라인',
    timelineEmpty: '다음 프로필부터 변화 기록이 쌓여요.',
    changeTitle: '이전 프로필과 달라진 지점',
    changeSince: '이전 기록 대비',
    changeStable: '6개 지표가 거의 같은 모양을 유지하고 있어요.',
    restore: '이 프로필로 복원',
    clearConfirm: '프로필, 피드백, Weekly Vibe 기록을 모두 지우고 다시 시작할까요?',
    cleared: 'V2 로컬 데이터를 모두 지웠어요.',
    shareCancelled: '공유를 취소했어요.',
    shareError: '주간 카드를 준비하지 못했어요.'
  }),
  en: Object.freeze({
    navWeekly: 'Weekly',
    openWeekly: 'Open this week’s Vibe',
    weeklyReady: 'Your weekly recap is ready',
    weeklyCollecting: 'Building your Weekly Vibe',
    weeklyReturn: 'See what your taste collected over seven days',
    weeklyEyebrow: 'WEEKLY VIBE',
    weeklyTitle: 'Where did your taste move this week?',
    weeklyDescription: 'A private recap built from seven days of contexts, track clicks, and feedback.',
    weeklyNeedMore: 'A few more interactions are needed for Weekly Vibe.',
    weeklyRemaining: 'more track choices or feedback signals to go.',
    weeklyContext: 'Most frequent moment',
    weeklyTags: 'Sounds of the week',
    weeklyTracks: 'Tracks worth revisiting',
    weeklyChanges: 'Movement from your core profile',
    weeklyShare: 'Share weekly card',
    weeklyDownload: 'Save weekly card',
    feedbackMore: 'More like this',
    feedbackLess: 'Less like this',
    feedbackSaved: 'Saved for your next recommendation.',
    timeline: 'Profile timeline',
    timelineEmpty: 'Changes will appear after your next profile.',
    changeTitle: 'What changed from the previous profile',
    changeSince: 'Compared with the previous snapshot',
    changeStable: 'The six dimensions stayed almost the same shape.',
    restore: 'Restore this profile',
    clearConfirm: 'Clear the profile, feedback, and Weekly Vibe history and start again?',
    cleared: 'All local V2 data was cleared.',
    shareCancelled: 'Share cancelled.',
    shareError: 'Could not prepare the weekly card.'
  })
});

export function retentionCopy(language) {
  return M4_COPY[language === 'en' ? 'en' : 'kr'];
}
